### ISSUE TITLE
Links from Answer Key direct to the wrong places

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2105]
On katalyst01 https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.4:UMWwtRqB@9.4/Answer-Key in Answer Key when ~~you click on~~ you right click on solution of some exercise and open link in new tab, link leads you to the next exercise on some page.

For Example:

when you ~~click on~~ click right on **21** and open link in new tab

![link_a_k](https://user-images.githubusercontent.com/40228854/49443771-93831d80-f7cd-11e8-95e8-657301c71833.JPG)

then you see exercise **23**

![link_sec](https://user-images.githubusercontent.com/40228854/49443823-b6153680-f7cd-11e8-9673-e949cdba7f9d.JPG)

**Comment by Adrianltd** [comment]
@wilkus27 could you please check this one again? I think there was some issue with latest content migration and now it's all good.

**Comment by wilkus27** [comment]
@Adrianltd I checked this and problem is still occuring.

**Comment by Adrianltd** [comment]
@helenemccarron it seems that this issue occurs only when you right click and open in new tab. When you try to open it in new tab with `cmd` or `ctrl`, it's prevented from opening in new tab by a script. When you open this on the same tab, there's no issue. 

The issue itself exists because the offset top is too low after opening in new tab - the menu covers that place which is being scrolled to.

At my localhost the problem doesn't exist, I've changed the offset in https://github.com/Connexions/webview/pull/2113 which should do the job, but @wilkus27 said that the problem still occurs on the server as it was before.

In my opinion this issue is rather very low priority and solving this might need a bigger understanding of how the page rendering works, which might take a lot of time.

**Comment by Adrianltd** [comment]
@openstaxalina can you read above and decide?

**Comment by openstaxalina** [comment]
@Adrianltd and @wilkus27 thank you for the analysis.  Yes, I figured the same thing about the menu covering the place it's meant to scroll to.  

I agree that this is overall a low-priority issue.  I'll move it to the Books backlog in case someone has time to investigate further in the future.
